Insta/urls.py
from django.contrib import admin
from django.urls import include, path

from Insta.views import (HelloWorld, PostsView, PostDetailView, 
                        addLike, PostCreateView, PostUpdateView, PostDeleteView, ExploreView,
                        UserDetailView, EditProfile, toggleFollow, addComment) 

urlpatterns = [
    path('helloworld/', HelloWorld.as_view(), name='helloWorld'), #当输入是空的时候返回hello world
    path('', PostsView.as_view(), name = 'posts'),#当传递进来的路径是posts的时候，我们会用PostsView.as_view()这个函数
    path('post/<int:pk>', PostDetailView.as_view(), name = 'post_detail'), #a key will be provided with the post and use it as primary key to render it.
    path('post/new/', PostCreateView.as_view(), name = 'make_post'),
    path('post/update/<int:pk>', PostUpdateView.as_view(), name = 'post_update'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name = 'post_delete'),
    path('like', addLike, name='addLike'),
    path('user/<int:pk>', UserDetailView.as_view(), name = 'user_detail'),
    path('edit_profile/<int:pk>/', EditProfile.as_view(), name = 'edit_profile'),
    path('togglefollow', toggleFollow, name = 'togglefollow'),
    path('comment', addComment, name='addComment'),
    path('explore', ExploreView.as_view(), name='explore'),

]

InstaJZ/urls.py
from django.contrib import admin
from django.urls import include, path

from Insta.views import SignUp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Insta.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/signup/', SignUp.as_view(), name = 'signup'),
    #对这个全局的urls的理解可以如下：
    #当输入的url是insta开头的话就交给insta这个app下面的urls.py来进行操作。
    #当输入的url是auth开头的话就交给django.contrib.auth这个app的urls来处理，而这个app是Django自身带有的。
]

Insta/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from django.urls import reverse 
from django.contrib.auth.models import AbstractUser
# Create your models here.

class InstaUser(AbstractUser): #在继承Django中自带的AbstractUser后再自己定义一个profile picture
    profile_pic = ProcessedImageField(
        upload_to = 'static/images/profiles', 
        format = 'JPEG',
        options = {'quality':100},
        blank = True,
        null = True,
    )

    def get_connections(self):
        connections = UserConnection.objects.filter(creator=self)
        return connections

    def get_followers(self):
        followers = UserConnection.objects.filter(following=self)
        return followers

    def is_followed_by(self, user):
        followers = UserConnection.objects.filter(following=self)
        return followers.filter(creator=user).exists()

    def get_absolute_url(self):
        return reverse('user_detail', args = [str(self.id)])

    def __str__(self):
        return self.username

class UserConnection(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    creator = models.ForeignKey(
        InstaUser,
        on_delete=models.CASCADE,
        related_name="friendship_creator_set")
    following = models.ForeignKey(
        InstaUser,
        on_delete=models.CASCADE,
        related_name="friend_set")

    def __str__(self):
        return self.creator.username + ' follows ' + self.following.username

class Post(models.Model): 
    author = models.ForeignKey( #Post也应该是一个foreign key，因为其应是指向某一个发这个post的用户
        InstaUser,
        on_delete = models.CASCADE,
        related_name = 'my_posts' #当我处于当前用户时，我可以通过my_posts来找到我发过的posts.
    )
    title = models.TextField(blank = True, null = True)
    image = ProcessedImageField(
        upload_to = 'static/images/posts', #image 都储存在post里面
        format = 'JPEG',
        options = {'quality':100},
        blank = True,
        null = True,
    )
    def get_like_count(self):
        return self.likes.count()

    #if someone create a post, it will redirect to get_absolute_url
    def get_absolute_url(self):
        return reverse("post_detail", args = [str(self.id)])

    posted_on = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )


class Like(models.Model):
    #这个like model应该告诉我们哪一个用户喜欢哪一个post
    #因此这个model应该是一个关系型model,其应该联系起Post和InstaUser之间的关系
    #Foreignkey 表示这个post并不是哪一个具体的类型，是一个外键，指向post这个model的一个key.
    #并且当post被删除时，Like这个关系也会被删除： on_delete = models.CASCADE
    #
    post = models.ForeignKey(
        Post,
        on_delete = models.CASCADE,
        related_name='likes')
    user = models.ForeignKey(
        InstaUser,
        on_delete = models.CASCADE,
        related_name = 'likes'
    )
    #这个like model里面定义了两个fields: post 和 user， 且他们都是外键，他们指向别的model: Post, InstaUser
    #而这个 “likes” 可以帮助在当前外键下找到作用于自己的Like这个关系，比如在某一篇Post下，通过'likes'便可以找到所有对
    #这篇Post点赞的user. 在User上反之便可找到所有自己点过的likes.

    class Meta:
        unique_together = ("post", "user")
        #一个user只可以给一篇post点一个赞
        #即同样的user和post只能出现一次
    
    def __str__(self):
            return 'Like: ' + self.user.username + ' likes ' + self.post.title




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments',)
    user = models.ForeignKey(InstaUser, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    posted_on = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.comment

templates/base.html
<html>
    {% load static %} 
    <head>
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>Hotel Cards</title> 
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/font-awesome-4.6.3/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        {% include 'header.html' %} 
 
        <div class="content-wrapper">
            <div class="container">
                {% block content %}
                {% endblock content%}
            </div>
        </div>

        <script type="text/javascript" src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/ajax-csrf-auth.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
        
        {% block extrascript %}
        {% endblock %}


    </body>
</html>

templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}

<div class="row profile-settings">
  <div class="col-xs-12">
    <div class="profile-pic-name">
      {% if user.profile_pic %}
        <img class="picture-circle--medium" src="http://{{ request.META.HTTP_HOST }}/{{user.profile_pic.url}}">
      {% endif %}
      <span class="username">{{ user.username }}</span>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
  </div>
</div>

{% endblock content %}

templates/explore.html
{% extends "base.html" %}

{% block content %}

<div class="row" id="explore">
  {% for post in object_list %}
    <div class="col-xs-4 col-sm-3">
      <div class="picture-square" style="background-image: url(http://{{ request.META.HTTP_HOST }}/{{ post.image.url }}); background-size: contain;">
        <a href="{% url 'post_detail' post.pk %}">
          <div class="content"></div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>


{% endblock %}

templates/header.html
<div class="navbar navbar-default navbar-fixed-top" id="main-nav">
    <div class="container desktop">
        <div class="navbar-header">
            <a href="{% url 'posts' %}" class="navbar-brand">JZ Insta</a>
        </div>

        <div id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'posts' %}">
                            <i class="fa fa-home" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li><a href="{% url 'explore' %}"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'make_post' %}"><i class="fa fa-plus" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'user_detail' user.id %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/index.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="cards-listing">
    {% for post in object_list %}
        <div class="row">
            <div class="card view-update {{ post.pk }}">

                <div class="card__panel-head">
                    <div class="poster__info">
                        <a href="{% url 'user_detail' post.author.id%}" class="poster__name">
                            {% if post.author.profile_pic %}
                                <img class="poster__profilepic" src="/{{ post.author.profile_pic }}">
                            {% endif %}
                            {{ post.author.username }}
                        </a>
                    </div>
                </div>

                <a href="{% url 'post_detail' post.pk %}">
                    <img class="card__main-image" src="/{{ post.image }}">
                </a>
                

                <div class="card__panel-body">
                    <div class="likes">
                        {% if post.get_like_count %}
                            {{ post.get_like_count }} like{% if post.get_like_count > 1 %}s{% endif %}
                        {% endif %}
                    </div>

                    <ul class="comment-list">
                        <a class="view-more"></a>
                        {% for comment in post.comments.all %}
                        <li class="comment-list__comment">
                            <a href="{% url 'user_detail' comment.user.pk %}" class="user">
                                {{ comment.user.username }}
                            </a>
                            <span class="comment">{{ comment.comment }}</span>
                        </li>
                        {% endfor %}
                    </ul>       

                    <section class = "input-row">
                        <i class="fa {% has_user_liked_post post user %} submit-like" aria-hidden="true"></i>
                        <div class="comment-input-wrapper">
                            <input class="add-comment" type="text" placeholder="Add a comment...">
                        </div>
                        <div class="hidden-data {{ post.pk }}" style="display: none;">
                            <span class="post-pk">{{ post.pk }}</span>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

templates/post_create.html
{% extends 'base.html' %}

{% block content %} 


<h1> New Post</h1>

<form action = "" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}


    <!-- <p>
        <label for="id_title">Title:</label>
        <textarea name="title" cols="40" rows="10" id="id_title">
        </textarea>
    </p>
    <p>
        <label for="id_image">Image:</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    </p>

    <button type = "submit">Save</button> -->

    <button type = "submit">Save</button>
</form>

{% endblock content %} 

templates/post_delete.html
{% extends 'base.html' %}

{% block content %} 


<h1> Delete Post</h1>

<form action = "" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    <p>Do you want to delete "{{post.title}}"?</p>
    <button type = "submit">Delete</button>
</form>

{% endblock content %} 

templates/post_detail.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="row single-post">
    <div class="single-post-card view-update {{ object.pk }}">
        <div class="header">
            <a href="{% url 'user_detail' object.author.pk %}">
                {% if object.author.profile_pic %}
                    <img class="picture-circle--medium" src="/{{object.author.profile_pic}}">
                {% endif %}
                {{ object.author.username }}
            </a>
        </div>

        <div class="image__wrapper">
            <img class="card__main-image" src="/{{object.image}}" width='1000', height='1000'>
        </div>

        <div class="comments-portion">
            <div class="likes-timestamp-row">
                <div class="likes">
                    {% if object.get_like_count %}
                        {{ object.get_like_count }} like{% if object.get_like_count > 1 %}s{% endif %}
                    {% endif %}
                </div>
            </div>

            <ul class="comment-list">
                {% for comment in object.comments.all %}
                <li class="comment-list__comment">
                    <a href="{% url 'user_detail' comment.user.pk %}" class="user">
                        {{ comment.user.username }}
                    </a>
                    <span class="comment">{{ comment.comment }}</span>
                </li>
                {% endfor %}
            </ul>

            <section class="input-row">
                <i class="fa {% has_user_liked_post post user %} submit-like" aria-hidden="true"></i>
                <div class="comment-input-wrapper">
                    <input class="add-comment" type="text" placeholder="Add a comment...">
                </div>
                <div class="hidden-data {{ object.pk }}" style="display: none;">
                    <span class="post-pk">{{ object.pk }}</span>
                </div>
            </section>
        </div>
    </div>
</div>

{% endblock content %}

templates/post_update.html
{% extends 'base.html' %}

{% block content %} 


<h1> Edit Post</h1>

<form action = "" method = "post" enctype = "multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Update</button>
</form>

{% endblock content %} 

templates/signup.html
{% extends 'base.html' %}

{% block content %} 

<h1> Sign Up</h1>

<form method = "post" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Sign up</button>
</form>


{% endblock content %} 

templates/test.html
hello world! from Scott

templates/user_detail.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}

<div class="profile">

    <div class="profile__head">
        <div class="row">
            <div class="col-xs-4 left">
                {% if object.profile_pic %}
                    <img class="picture-circle" src="/{{object.profile_pic}}">
                {% endif %}
            </div>
            <div class="col-xs-8 right">
                <div class="name-buttons">
                    <h1 class="username">{{ object.username }}</h1>
                    {% if user == object %}
                        <a class="edit-desktop" href="{% url 'edit_profile' object.pk %}">
                            <button class="edit-profile">Edit Profile</button>
                    {% else %}
                        {% is_following user object as following %}
                        <div class="follow-toggle__container">
                            <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ object.pk }}">
                                {% if following %}
                                    Unfollow
                                {% else %}
                                    Follow
                                {% endif %}
                            </button>
                        </div>
                    {% endif %}
                </div>

                <div>
                    <ul class="stats">
                        <div class="col-xs-4"><li class="stats__count"><span>{{ object.my_posts.count }}</span><br> posts</li></div>
                        <div class="col-xs-4"><a href="/" style="text-decoration: none; color: black;"><li class="stats__count"><span class="follower_count" id="follower_id">{{ object.get_followers.count }}</span><br> followers</li></a></div>
                        <div class="col-xs-4"><a href="/" style="text-decoration: none; color: black;"><li class="stats__count"><span>{{ object.get_connections.count }}</span><br> following</li></a></div>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="profile__body">
        <div class="row">
        {% for post in object.my_posts.all %}
            <div class="col-xs-4">
                <div class="picture-square" style="background-image: url(http://{{ request.META.HTTP_HOST }}/{{ post.image.url }}); background-size: contain;">
                    <a href="{% url 'post_detail' post.pk %}">
                    <div class="content">
                        <i class="fa fa-heart" aria-hidden="true"></i> {{ post.get_like_count }}
                    </div>
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}